//
// Generated file, do not edit! Created by opp_msgtool 6.2 from src/messages.msg.
//

#ifndef __MESSAGES_M_H
#define __MESSAGES_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0602
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class EnhancedNetMsg;
class AckMessage;
class RouteUpdateMsg;
class HeartbeatMsg;
/**
 * Class generated from <tt>src/messages.msg:5</tt> by opp_msgtool.
 * <pre>
 * //
 * // EnhancedNetMsg - 增强型网络消息
 * // 相比原版新增：TTL、跳数计数、序列号、重传标志
 * //
 * message EnhancedNetMsg
 * {
 *     int messageId = 0;              // 消息唯一标识
 *     int sourceNode = -1;             // 源节点编号
 *     int destNode = -1;               // 目的节点编号
 *     int sequenceNum = 0;             // 序列号（用于重传检测）
 *     simtime_t creationTime;          // 消息创建时间
 *     int ttl = 10;                    // 生存时间（防止路由循环）
 *     int hopCount = 0;                // 已跳数计数
 *     bool retransmission = false;     // 是否为重传消息
 *     string payload = "";             // 消息内容负载
 * }
 * </pre>
 */
class EnhancedNetMsg : public ::omnetpp::cMessage
{
  protected:
    int messageId = 0;
    int sourceNode = -1;
    int destNode = -1;
    int sequenceNum = 0;
    omnetpp::simtime_t creationTime = SIMTIME_ZERO;
    int ttl = 10;
    int hopCount = 0;
    bool retransmission = false;
    omnetpp::opp_string payload = "";

  private:
    void copy(const EnhancedNetMsg& other);

  protected:
    bool operator==(const EnhancedNetMsg&) = delete;

  public:
    EnhancedNetMsg(const char *name=nullptr, short kind=0);
    EnhancedNetMsg(const EnhancedNetMsg& other);
    virtual ~EnhancedNetMsg();
    EnhancedNetMsg& operator=(const EnhancedNetMsg& other);
    virtual EnhancedNetMsg *dup() const override {return new EnhancedNetMsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getMessageId() const;
    virtual void setMessageId(int messageId);

    virtual int getSourceNode() const;
    virtual void setSourceNode(int sourceNode);

    virtual int getDestNode() const;
    virtual void setDestNode(int destNode);

    virtual int getSequenceNum() const;
    virtual void setSequenceNum(int sequenceNum);

    virtual omnetpp::simtime_t getCreationTime() const;
    virtual void setCreationTime(omnetpp::simtime_t creationTime);

    virtual int getTtl() const;
    virtual void setTtl(int ttl);

    virtual int getHopCount() const;
    virtual void setHopCount(int hopCount);

    virtual bool getRetransmission() const;
    virtual void setRetransmission(bool retransmission);

    virtual const char * getPayload() const;
    virtual void setPayload(const char * payload);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const EnhancedNetMsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, EnhancedNetMsg& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>src/messages.msg:21</tt> by opp_msgtool.
 * <pre>
 * //
 * // AckMessage - 确认消息
 * // 用于可靠性传输：目的节点收到数据后回复ACK
 * //
 * message AckMessage
 * {
 *     int ackId = 0;                  // ACK唯一标识
 *     int sourceNode = -1;             // ACK发送者（目的节点）
 *     int destNode = -1;               // ACK接收者（源节点）
 *     int sequenceNum = 0;             // 被确认的消息序列号
 *     simtime_t sendTime;              // ACK发送时间
 * }
 * </pre>
 */
class AckMessage : public ::omnetpp::cMessage
{
  protected:
    int ackId = 0;
    int sourceNode = -1;
    int destNode = -1;
    int sequenceNum = 0;
    omnetpp::simtime_t sendTime = SIMTIME_ZERO;

  private:
    void copy(const AckMessage& other);

  protected:
    bool operator==(const AckMessage&) = delete;

  public:
    AckMessage(const char *name=nullptr, short kind=0);
    AckMessage(const AckMessage& other);
    virtual ~AckMessage();
    AckMessage& operator=(const AckMessage& other);
    virtual AckMessage *dup() const override {return new AckMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getAckId() const;
    virtual void setAckId(int ackId);

    virtual int getSourceNode() const;
    virtual void setSourceNode(int sourceNode);

    virtual int getDestNode() const;
    virtual void setDestNode(int destNode);

    virtual int getSequenceNum() const;
    virtual void setSequenceNum(int sequenceNum);

    virtual omnetpp::simtime_t getSendTime() const;
    virtual void setSendTime(omnetpp::simtime_t sendTime);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const AckMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, AckMessage& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>src/messages.msg:33</tt> by opp_msgtool.
 * <pre>
 * //
 * // RouteUpdateMsg - 路由更新消息
 * // 用于路由表维护：节点间交换路由信息
 * //
 * message RouteUpdateMsg
 * {
 *     int updateId = 0;                // 更新消息ID
 *     int sourceNode = -1;             // 发送更新的节点
 *     simtime_t updateTime;            // 更新时间
 *     int destCount = 0;               // 路由条目数量
 * 
 *     // 路由信息数组（动态大小，由destCount决定）
 *     // 格式：destNode:metric:nextHop:sequnce
 *     string routeEntries[];           // 路由条目列表
 * }
 * </pre>
 */
class RouteUpdateMsg : public ::omnetpp::cMessage
{
  protected:
    int updateId = 0;
    int sourceNode = -1;
    omnetpp::simtime_t updateTime = SIMTIME_ZERO;
    int destCount = 0;
    omnetpp::opp_string *routeEntries = nullptr;
    size_t routeEntries_arraysize = 0;

  private:
    void copy(const RouteUpdateMsg& other);

  protected:
    bool operator==(const RouteUpdateMsg&) = delete;

  public:
    RouteUpdateMsg(const char *name=nullptr, short kind=0);
    RouteUpdateMsg(const RouteUpdateMsg& other);
    virtual ~RouteUpdateMsg();
    RouteUpdateMsg& operator=(const RouteUpdateMsg& other);
    virtual RouteUpdateMsg *dup() const override {return new RouteUpdateMsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getUpdateId() const;
    virtual void setUpdateId(int updateId);

    virtual int getSourceNode() const;
    virtual void setSourceNode(int sourceNode);

    virtual omnetpp::simtime_t getUpdateTime() const;
    virtual void setUpdateTime(omnetpp::simtime_t updateTime);

    virtual int getDestCount() const;
    virtual void setDestCount(int destCount);

    virtual void setRouteEntriesArraySize(size_t size);
    virtual size_t getRouteEntriesArraySize() const;
    virtual const char * getRouteEntries(size_t k) const;
    virtual void setRouteEntries(size_t k, const char * routeEntries);
    virtual void insertRouteEntries(size_t k, const char * routeEntries);
    [[deprecated]] void insertRouteEntries(const char * routeEntries) {appendRouteEntries(routeEntries);}
    virtual void appendRouteEntries(const char * routeEntries);
    virtual void eraseRouteEntries(size_t k);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const RouteUpdateMsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, RouteUpdateMsg& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>src/messages.msg:48</tt> by opp_msgtool.
 * <pre>
 * //
 * // HeartbeatMsg - 心跳消息
 * // 用于链路监测：检测邻居节点和链路状态
 * //
 * message HeartbeatMsg
 * {
 *     int heartbeatId = 0;             // 心跳ID
 *     int sourceNode = -1;             // 发送心跳的节点
 *     int targetNode = -1;             // 目标邻居节点
 *     simtime_t sendTime;              // 发送时间
 *     bool isAlive = true;             // 节点是否存活
 * }
 * </pre>
 */
class HeartbeatMsg : public ::omnetpp::cMessage
{
  protected:
    int heartbeatId = 0;
    int sourceNode = -1;
    int targetNode = -1;
    omnetpp::simtime_t sendTime = SIMTIME_ZERO;
    bool isAlive_ = true;

  private:
    void copy(const HeartbeatMsg& other);

  protected:
    bool operator==(const HeartbeatMsg&) = delete;

  public:
    HeartbeatMsg(const char *name=nullptr, short kind=0);
    HeartbeatMsg(const HeartbeatMsg& other);
    virtual ~HeartbeatMsg();
    HeartbeatMsg& operator=(const HeartbeatMsg& other);
    virtual HeartbeatMsg *dup() const override {return new HeartbeatMsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getHeartbeatId() const;
    virtual void setHeartbeatId(int heartbeatId);

    virtual int getSourceNode() const;
    virtual void setSourceNode(int sourceNode);

    virtual int getTargetNode() const;
    virtual void setTargetNode(int targetNode);

    virtual omnetpp::simtime_t getSendTime() const;
    virtual void setSendTime(omnetpp::simtime_t sendTime);

    virtual bool isAlive() const;
    virtual void setIsAlive(bool isAlive);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const HeartbeatMsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, HeartbeatMsg& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline EnhancedNetMsg *fromAnyPtr(any_ptr ptr) { return check_and_cast<EnhancedNetMsg*>(ptr.get<cObject>()); }
template<> inline AckMessage *fromAnyPtr(any_ptr ptr) { return check_and_cast<AckMessage*>(ptr.get<cObject>()); }
template<> inline RouteUpdateMsg *fromAnyPtr(any_ptr ptr) { return check_and_cast<RouteUpdateMsg*>(ptr.get<cObject>()); }
template<> inline HeartbeatMsg *fromAnyPtr(any_ptr ptr) { return check_and_cast<HeartbeatMsg*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __MESSAGES_M_H

