//
// Generated file, do not edit! Created by opp_msgtool 6.2 from src/messages.msg.
//

#ifndef __MESSAGES_M_H
#define __MESSAGES_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0602
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class NetMessage;
/**
 * Class generated from <tt>src/messages.msg:6</tt> by opp_msgtool.
 * <pre>
 * message NetMessage
 * {
 *     int messageId = 0;           // 消息唯一标识
 *     int sourceNode = -1;          // 源节点编号
 *     int destNode = -1;            // 目的节点编号
 *     simtime_t creationTime;       // 消息创建时间（用于计算端到端延迟）
 *     string payload = "";          // 消息内容负载
 * }
 * </pre>
 */
class NetMessage : public ::omnetpp::cMessage
{
  protected:
    int messageId = 0;
    int sourceNode = -1;
    int destNode = -1;
    omnetpp::simtime_t creationTime = SIMTIME_ZERO;
    omnetpp::opp_string payload = "";

  private:
    void copy(const NetMessage& other);

  protected:
    bool operator==(const NetMessage&) = delete;

  public:
    NetMessage(const char *name=nullptr, short kind=0);
    NetMessage(const NetMessage& other);
    virtual ~NetMessage();
    NetMessage& operator=(const NetMessage& other);
    virtual NetMessage *dup() const override {return new NetMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getMessageId() const;
    virtual void setMessageId(int messageId);

    virtual int getSourceNode() const;
    virtual void setSourceNode(int sourceNode);

    virtual int getDestNode() const;
    virtual void setDestNode(int destNode);

    virtual omnetpp::simtime_t getCreationTime() const;
    virtual void setCreationTime(omnetpp::simtime_t creationTime);

    virtual const char * getPayload() const;
    virtual void setPayload(const char * payload);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const NetMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, NetMessage& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline NetMessage *fromAnyPtr(any_ptr ptr) { return check_and_cast<NetMessage*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __MESSAGES_M_H

